syntax on
filetype plugin indent on
set nobackup
set noswapfile
set noundofile
set nu
set relativenumber
set autoindent
set title
set tabstop=4
set shiftwidth=4
set expandtab
set autoread
set smartcase
set ignorecase
set incsearch
highlight Comment ctermfg=green
nnoremap K :m .-2<CR>==
inoremap J <Esc>:m .+1<CR>==gi
inoremap K <Esc>:m .-2<CR>==gi
vnoremap J :m '>+1<CR>gv=gv
vnoremap K :m '<-2<CR>gv=gv
map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l
