syntax enable
set nocompatible
set encoding=utf8

filetype plugin on
filetype indent on

set nu
set relativenumber

set wildmenu
set so=10
set ai
set si
set wrap

set smartcase
set hlsearch

set noundofile
set nobackup
set noswapfile

let mapleader = " "
map <leader>rv :e! ~/.vimrc<cr>
map <leader>pv :Ex<cr>
" Insert empty line below
nmap <silent> <leader><CR> o<ESC>

highlight Comment ctermfg=green

