export TERM="xterm-256color"
export ZSH="$HOME/.oh-my-zsh"

# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="lambda"

plugins=(
    aws
    docker
    git
    macos
    kubectx
    # vi-mode
    zsh-autosuggestions
    zsh-syntax-highlighting
    fast-syntax-highlighting
    zsh-autocomplete
)
source $ZSH/oh-my-zsh.sh

export EDITOR="nvim"

alias ll="ls -l"
alias lla="ls -la"
alias myip="curl ipinfo.io/ip"
alias g="git"
alias k9="kill -9"
alias chex="chmod +x"
alias cd.="cd ../"
alias cd..="cd ../../"
alias cd...="cd ../../../"
alias cat="bat"
alias uuid="python -c 'from uuid import uuid4; print(str(uuid4()))'"
alias kube="kubectl"

