export ZSH="$HOME/.oh-my-zsh"
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="lambda"

plugins=(
    aws
    docker
    git
    macos
    kubectx
    # vi-mode
    zsh-autosuggestions
    zsh-completions
    zsh-syntax-highlighting
)
source $ZSH/oh-my-zsh.sh

# Preferred editor for local and remote sessions
# if [[ -n $SSH_CONNECTION ]]; then
#   export EDITOR='vim'
# else
#   export EDITOR='mvim'
# fi
export EDITOR="nvim"

alias ll="ls -l"
alias lla="ls -la"
alias myip="curl ipinfo.io/ip"
alias g="git"
alias k9="kill -9"
alias chex="chmod +x"
alias cd.="cd ../"
alias cd..="cd ../../"
alias cd...="cd ../../../"
alias cat="bat"
alias uuid="python -c 'from uuid import uuid4; print(str(uuid4()))'"
